Upgrade project config
gravitee-io/gravitee-policy-transformheaders pull request #24
Opened 2022-01-21 14:14 UTC by gcusnieux

2022-01-21 14:17 UTC, phiz71 approved these changes

2022-01-21 14:24 UTC, a-cordier requested changes

2022-01-21 14:24 UTC, a-cordier commented on pom.xml
> +        <publish-folder-path>y</publish-folder-path>
```suggestion
        <publish-folder-path>graviteeio-apim/plugins/policies</publish-folder-path>
```

2022-01-21 15:03 UTC, ThibaudAV approved these changes

2022-01-21 15:07 UTC, phiz71 approved these changes

2022-01-21 15:08 UTC, a-cordier approved these changes

2022-01-21 15:09 UTC, merged

2022-01-21 15:12 UTC, graviteeio commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on:
- `1.9.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-transformheaders/releases/tag/1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-01-21 15:40 UTC, graviteeio commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on:
- `1.9.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-transformheaders/releases/tag/1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-01-22 17:43 UTC, graviteeio commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on:
- `1.9.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-transformheaders/releases/tag/1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: