feat: Add support for request / response's payload to define HTTP hea…
gravitee-io/gravitee-policy-transformheaders pull request #29
Opened 2022-03-21 07:17 UTC by brasseld

…ders values

Closes gravitee-io/issues#7333

2022-03-21 08:06 UTC, ytvnr requested changes
It's currently not working for me. (see comment for `BufferedReadWriteStream#end()`)

Can you also do the PRs for `gravitee-api-management/gravitee-apim-distribution/pom.xml `and `release.json` please?

2022-03-21 08:06 UTC, ytvnr commented on src/main/java/io/gravitee/policy/transformheaders/TransformHeadersPolicy.java
> +                }
It ends in timeout without that (both with postman or debug mode):

```suggestion
                }
                
                if (buffer.length() > 0) {
                    super.write(buffer);
                }

                super.end();
```

2022-03-21 13:34 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/transformheaders/TransformHeadersPolicy.java
> +                }
I think a call to `super.end()` is missing here no ? Without it I think it breaks the execution chain. WDYT ?

2022-03-22 12:04 UTC, gcusnieux commented
Hi @brasseld, 
After the last fix on gateway, I wonder if we should not make an `add` rather than a `set` here: https://github.com/gravitee-io/gravitee-policy-transformheaders/blob/master/src/main/java/io/gravitee/policy/transformheaders/TransformHeadersPolicy.java#L91

2022-03-22 13:05 UTC, ytvnr requested changes
is failing because of a wrong dependency in pom.xml

2022-03-23 06:56 UTC, ytvnr approved these changes
lgtm

2022-03-23 17:28 UTC, phiz71 approved these changes

2022-03-24 07:58 UTC, merged

2022-03-24 08:01 UTC, graviteeio commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on:
- `1.10.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-transformheaders/releases/tag/1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-13 12:31 UTC, graviteeio commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on [GitHub release](https://github.com/gravitee-io/gravitee-policy-transformheaders/releases/tag/1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: